# Generated by Django 5.0.6 on 2024-07-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbc',
            options={'verbose_name_plural': 'BBC'},
        ),
    ]
